dependencies:
  - name: kashti
    version: 0.1.1
    repository: https://brigadecore.github.io/charts
    condition: kashti.enabled
  - name: brigade-github-app
    version: 0.1.2
    repository: https://brigadecore.github.io/charts
    condition: brigade-github-app.enabled
  - name: brigade-github-oauth
    alias: gw
    version: 0.1.0
    repository: https://brigadecore.github.io/charts
    condition: gw.enabled