{{ if .Values.genericGateway.enabled }}
{{ $fullname := include "brigade.genericGateway.fullname" . }}
{{ $serviceAccount := default $fullname .Values.genericGateway.serviceAccount.name }}
apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: gateway
    type: generic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "brigade.fullname" . }}
      app: {{ template "brigade.fullname" . }}
      role: gateway
      type: generic
  template:
    metadata:
    {{- if .Values.genericGateway.podAnnotations }}
      annotations:
{{ toYaml .Values.genericGateway.podAnnotations | indent 8}}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "brigade.fullname" . }}
        app: {{ template "brigade.fullname" . }}
        role: gateway
        type: generic
    spec:
      serviceAccountName: {{ $serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.genericGateway.registry }}/{{ .Values.genericGateway.name }}:{{ default .Chart.AppVersion .Values.genericGateway.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.genericGateway.pullPolicy }}
        ports:
        - containerPort: {{ .Values.genericGateway.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.genericGateway.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.genericGateway.service.internalPort }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}
{{ end }}
