apiVersion: v1
description: The Brigade GitHub App, an advanced gateway for GitHub
name: brigade-github-app
sources:
  - https://github.com/brigadecore/brigade-github-app
version: 0.0.1
# Note that we use appVersion to get images, so make sure this is correct.
appVersion: v0.1.0
