--- {{ $fname := include "gateway.fullname" . }}
{{ $serviceAccount := default $fname .Values.serviceAccount.name }}
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
  labels:
    app: {{ template "gateway.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ end }}
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "gateway.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "gateway.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["list", "watch", "get", "create"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "watch"]
---
kind: RoleBinding
apiVersion: {{ template "gateway.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "gateway.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ $fname }}
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
